# Generated by Django 5.0.1 on 2024-04-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='tilte',
            new_name='title',
        ),
    ]
